on: [workflow_dispatch]

name: DeployMainBicep

jobs:
  deploy_main_bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get CarbonAware metrics
        id: carbonaware-metrics
        uses: webtonize/carbon-aware-sdk@dev
        with:
          location: westeurope,northeurope,swedencentral,uksouth,francecentral,germanywestcentral,norwayeast,francesouth,germanynorth,norwaywest,ukwest

      - uses: azure/arm-deploy@v1
        name: Run What-If bicep deployment
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          region: ${{ steps.carboneaware-metrics.outputs.LowestEmissionsLocation }}
          template: src/bicep/main.bicep
          additionalArguments: "--what-if"

      - uses: azure/arm-deploy@v1
        name: Run Bicep deployment
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          region: ${{ steps.carboneaware-metrics.outputs.LowestEmissionsLocation }}
          template: src/bicep/main.bicep
