# File: .github/workflows/validate-bicep.yml

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'releases/**'

name: Validate Bicep code

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: PSRule analysis
      uses: microsoft/ps-rule@v2.8.0
      with:
        modules: PSRule.Rules.Azure
        inputType: repository
        outputFormat: Sarif
        outputPath: ./psrule.sarif
        outcome: Processed

    - name: Upload PSRule SARIF results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: psrule.sarif

    - name: Build Bicep
      run: bicep build src/bicep/main.bicep

    - name: Get WattTime carbon emission metrics
      id: watttime_action
      uses: cloudyspells/PSWattTime@v1.0.5
      with:
        regions: westeurope,northeurope,swedencentral,uksouth,francecentral,germanywestcentral,norwayeast,francesouth,germanynorth,norwaywest,ukwest
        azure_credential: ${{ secrets.AZURE_CREDENTIALS }}
        watttime_username: ${{ secrets.DATASOURCES__CONFIGURATIONS__WATTTIME__USERNAME }}
        watttime_password: ${{ secrets.DATASOURCES__CONFIGURATIONS__WATTTIME__PASSWORD }}
      
    - name: Run What-If bicep deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: ${{ steps.watttime_action.outputs.region }}
        deploymentName: 'main-${{ steps.watttime_action.outputs.region }}'
        template: src/bicep/main.bicep
        additionalArguments: "--what-if"
