# File: .github/workflows/validate-bicep.yml

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'releases/**'

name: Validate Bicep code

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      security-events: write
    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: PSRule analysis
      uses: microsoft/ps-rule@v2.7.0
      with:
        modules: PSRule.Rules.Azure,PSRule.Rules.Azure
        inputType: repository
        outputFormat: None
        outcome: Processed

    - name: Build Bicep
      run: bicep build src/bicep/main.bicep

    - name: Get CarbonAware metrics
      id: carbonaware-metrics
      uses: Green-Software-Foundation/carbon-aware-sdk@1.1.0-Release
      with:
        location: westeurope,northeurope,swedencentral,uksouth,francecentral,germanywestcentral,norwayeast,francesouth,germanynorth,norwaywest,ukwest
      
    - name: Run What-If bicep depployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: subscription
        region: ${{ steps.carboneaware-metrics.outputs.LowestEmissionsLocation }}
        template: src/bicep/main.bicep
        additionalArguments: "--what-if"
